services:
  sqlserver:
    image: ghcr.io/rails-sqlserver/mssql-server-linux-rails
  ci:
    environment:
      - ACTIVERECORD_UNITTEST_HOST=sqlserver
      - RAILS_BRANCH=8-1-stable
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: wait-for sqlserver:1433 -- bundle exec rake test
    depends_on:
      - "sqlserver"
  standardrb:
    environment:
      - RAILS_BRANCH=8-1-stable
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: bundle exec standardrb
