services:
  sqlserver:
    image: ghcr.io/rails-sqlserver/mssql-server-linux-rails
  ci:
    environment:
      - ACTIVERECORD_UNITTEST_HOST=sqlserver
      - RAILS_COMMIT=65dc2163e3
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: wait-for sqlserver:1433 -- bundle exec rake test
    depends_on:
      - "sqlserver"
  standardrb:
    environment:
      - RAILS_COMMIT=65dc2163e3
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: bundle exec standardrb
