version: "2.2"
services:
  sqlserver:
    image: ghcr.io/rails-sqlserver/mssql-server-linux-rails
  ci:
    environment:
      - ACTIVERECORD_UNITTEST_HOST=sqlserver
      - RAILS_BRANCH=0b3320bcd5e705302b5707bcf27a80537b812c1f
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: wait-for sqlserver:1433 -- bundle exec rake test
    depends_on:
      - "sqlserver"
