version: '3'

services:
  activerecord-sqlserver-adapter:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - default

    depends_on:
      - sqlserver

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    networks:
      - default
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: MSSQLadmin!
      ACCEPT_EULA: Y

networks:
  default:

volumes:
  sqlserver-data:
